name: echo_garden
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  uuid: ^4.3.3
  fast_noise: ^2.0.0
  spritewidget: ^2.0.1
  flame: ^1.14.0
  flame_tiled: ^1.18.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

